const fakeData = [
  {
    name: 'Chest day',
    description: 'Monday',
    exercises: [
      {
        name: 'Flexões',
        description: '4x 10',
        restTime: 45,
        notes: null,
        order: 0,
      },
      {
        name: 'Chest Press',
        description: '4x 12/10/8/6',
        restTime: 45,
        notes: 'Convergente',
        order: 1,
      },
      {
        name: 'Supino Inclinado',
        description: '4x 12',
        restTime: 45,
        notes: 'Halters',
        order: 2,
      },
      {
        name: 'Abertura',
        description: '4x 10',
        restTime: 45,
        notes: 'Plano',
        order: 3,
      },
      {
        name: 'Cross Over',
        description: '4x 12',
        restTime: 45,
        notes: 'Polia Alta',
        order: 4,
      },
      {
        name: 'Crunch Mola',
        description: '4x 20',
        restTime: 45,
        notes: null,
        order: 5,
      },
      {
        name: 'Prancha',
        description: '4x Max',
        restTime: 45,
        notes: null,
        order: 6,
      },
      {
        name: 'Cardio',
        description: '10 minutes',
        restTime: 0,
        notes: null,
        order: 7,
      },
    ],
    order: 0,
  },
  {
    name: 'Leg day',
    description: 'Tuesday',
    exercises: [
      {
        name: 'Agachamentos',
        description: '4x 12/10/8/6',
        restTime: 45,
        notes: 'Multitower',
        order: 0,
      },
      {
        name: 'Prensa',
        description: '4x 12/10/8/6',
        restTime: 45,
        notes: null,
        order: 1,
      },
      {
        name: 'Lunge',
        description: '4x 10 (Each leg)',
        restTime: 45,
        notes: 'Estático',
        order: 2,
      },
      {
        name: 'Extensão',
        description: '4x 12',
        restTime: 45,
        notes: null,
        order: 3,
      },
      {
        name: 'Stiff',
        description: '4x 12',
        restTime: 45,
        notes: null,
        order: 4,
      },
      {
        name: 'Flexora',
        description: '4x 10',
        restTime: 45,
        notes: null,
        order: 5,
      },
      {
        name: 'Gemeos',
        description: '4x 10',
        restTime: 45,
        notes: 'Prensa',
        order: 6,
      },
    ],
    order: 1,
  },
  {
    name: 'Back day',
    description: 'Wednesday',
    exercises: [
      {
        name: 'Puxador Frente',
        description: '4x 12/10/8/6',
        restTime: 45,
        notes: null,
        order: 0,
      },
      {
        name: 'Puxador Neutro',
        description: '4x 12/10/8/6',
        restTime: 45,
        notes: 'Pega neutra',
        order: 1,
      },
      {
        name: 'Remada Baixa',
        description: '4x 12/10/8/6',
        restTime: 45,
        notes: null,
        order: 2,
      },
      {
        name: 'Serrote',
        description: '4x 10',
        restTime: 45,
        notes: null,
        order: 3,
      },
      {
        name: 'Lombar',
        description: '4x 20',
        restTime: 45,
        notes: 'Banco de Lombares',
        order: 4,
      },
      {
        name: 'Mountain Climber',
        description: '4x 20',
        restTime: 45,
        notes: null,
        order: 5,
      },
      {
        name: 'Flutter Kick',
        description: '4x 20',
        restTime: 45,
        notes: null,
        order: 6,
      },
      {
        name: 'Cardio',
        description: '10 minutes',
        restTime: 0,
        notes: null,
        order: 7,
      },
    ],
    order: 2,
  },
  {
    name: 'Shoulder day',
    description: 'Thursday',
    exercises: [
      {
        name: 'Press',
        description: '4x 12/10/8/6',
        restTime: 45,
        notes: 'Ombro halters',
        order: 0,
      },
      {
        name: 'Elevação Frontal',
        description: '4x 12',
        restTime: 45,
        notes: 'Disco',
        order: 1,
      },
      {
        name: 'Elevação Lateral',
        description: '4x 12',
        restTime: 45,
        notes: null,
        order: 2,
      },
      {
        name: 'Remada Alta',
        description: '4x 12',
        restTime: 45,
        notes: 'Cabo',
        order: 3,
      },
      {
        name: 'Face Pull',
        description: '4x 12',
        restTime: 45,
        notes: null,
        order: 4,
      },
      {
        name: 'Cardio',
        description: '10 minutes',
        restTime: 0,
        notes: null,
        order: 6,
      },
    ],
    order: 3,
  },
  {
    name: 'Arms day',
    description: 'Friday',
    exercises: [
      {
        name: 'Bicep Curl',
        description: '4x 12/10/8/6',
        restTime: 45,
        notes: 'Barra',
        order: 0,
      },
      {
        name: 'Bicep Martelo',
        description: '4x 12',
        restTime: 45,
        notes: 'Cabo',
        order: 1,
      },
      {
        name: 'Bicep Rotação',
        description: '4x 12',
        restTime: 45,
        notes: 'Halters',
        order: 2,
      },
      {
        name: 'Tricep Françes',
        description: '4x 12',
        restTime: 45,
        notes: 'Alter',
        order: 3,
      },
      {
        name: 'Tricep Corda',
        description: '4x 12',
        restTime: 45,
        notes: null,
        order: 4,
      },
      {
        name: 'Fundos',
        description: '4x 20',
        restTime: 45,
        notes: 'Banco',
        order: 5,
      },
      {
        name: 'Crunch Curto',
        description: '4x 20',
        restTime: 45,
        notes: null,
        order: 6,
      },
      {
        name: 'Russian Twist',
        description: '4x 20',
        restTime: 45,
        notes: null,
        order: 7,
      },
    ],
    order: 4,
  },
];

export default fakeData;
